alias ga="git add"
alias gb="git branch"
alias gbformat="git branch -a --sort=committerdate --format='%(committerdate:short) | %(committername) | %(refname:short)' | column -t -s '|'"
alias gc="git commit"
alias gdt="git difftool --tool=kdiff3 --no-prompt"
alias gs="git status -s"
